from typing import Any, Dict, List, Optional, Sequence, Tuple

class LDAPObject:
    def search_s(self, base: str, scope: int, filterstr: Optional[str] = ..., attrlist: Optional[Sequence[str]] = ..., attrsonly: int = ..., timeout: int = ...) -> List[Tuple[str, Dict[str, List[bytes]]]]: ...
    def set_option(self, option: int, invalue: int) -> None: ...
    def simple_bind(self, who: Optional[str] = ..., cred: Optional[str] = ..., serverctrls: Optional[Any] = ..., clientctrls: Optional[Any] = ...) -> int: ...
    def simple_bind_s(self, username: str, password: str) -> None: ...
    def unbind(self) -> None: ...
